#!/usr/bin/env bash
#
# Installer for aw5d-lcd — drives the iBUYPOWER AW5D cooler LCD on Linux.
#
# Installs:
#   * the driver           -> ~/.local/share/aw5d-lcd/aw5d_lcd.py
#   * an `aw5d-lcd` command -> ~/.local/bin/aw5d-lcd  (symlink; on PATH, no sudo)
#   * a udev rule          -> /etc/udev/rules.d/99-aw5d-lcd.rules   (needs sudo)
#   * a systemd user unit  -> ~/.config/systemd/user/aw5d-lcd.service
# then enables + starts the service and turns on lingering so the screen keeps
# updating even with no active login session (or after a crash to the desktop).
#
# Usage:  ./install.sh          (install + start)
#         ./install.sh --uninstall
#
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SHARE_DIR="$HOME/.local/share/aw5d-lcd"
UNIT_DIR="$HOME/.config/systemd/user"
UDEV_RULE="/etc/udev/rules.d/99-aw5d-lcd.rules"
SERVICE="aw5d-lcd.service"
# Where the `aw5d-lcd` command goes. Override with AW5D_BIN_DIR, e.g.
#   AW5D_BIN_DIR=/usr/local/bin ./install.sh   (system-wide; may prompt for sudo on write)
BIN_DIR="${AW5D_BIN_DIR:-$HOME/.local/bin}"
LAUNCHER="$BIN_DIR/aw5d-lcd"

log() { printf '\033[1;36m[aw5d-lcd]\033[0m %s\n' "$*"; }

# Find a Python 3.8+ interpreter (prefers python3, falls back to python).
# 3.8 is the floor because the driver uses bytes.hex(sep=…).
PYTHON=""
detect_python() {
    local name path
    for name in python3 python; do
        path="$(command -v "$name" 2>/dev/null)" || continue
        if "$path" -c 'import sys; raise SystemExit(0 if sys.version_info >= (3, 8) else 1)' 2>/dev/null; then
            PYTHON="$path"
            return 0
        fi
    done
    return 1
}

uninstall() {
    log "stopping + disabling service"
    systemctl --user disable --now "$SERVICE" 2>/dev/null || true
    rm -f "$UNIT_DIR/$SERVICE"
    systemctl --user daemon-reload 2>/dev/null || true
    rm -rf "$SHARE_DIR" "$HOME/.local/share/aw5d-lcd-src"
    rm -f "$HOME/.config/aw5d-lcd.env"
    rm -f "$LAUNCHER" 2>/dev/null || sudo rm -f "$LAUNCHER"
    if [[ -f "$UDEV_RULE" ]]; then
        log "removing udev rule (sudo)"
        sudo rm -f "$UDEV_RULE"
        sudo udevadm control --reload-rules || true
    fi
    log "uninstalled. (linger left enabled; disable with: loginctl disable-linger $USER)"
}

# NOTE: do NOT name this function `install` — it would shadow the coreutils
# `install` command used below and recurse infinitely.
do_install() {
    if ! detect_python; then
        echo "[aw5d-lcd] error: Python 3.8+ is required (tried 'python3' and 'python')." >&2
        echo "[aw5d-lcd]        install Python 3 and retry (Bazzite/Fedora ship it as 'python3')." >&2
        exit 1
    fi
    log "preflight: python $("$PYTHON" -c 'import sys;print(".".join(map(str,sys.version_info[:3])))') at $PYTHON"

    # This is a systemd --user service, so a user session bus is required. Check it up front
    # and fail with a clear message instead of aborting mid-install under `set -e` later
    # (e.g. `curl | bash` over a bare SSH session with no XDG_RUNTIME_DIR).
    if ! systemctl --user show-environment >/dev/null 2>&1; then
        echo "[aw5d-lcd] error: no systemd --user session (systemctl --user can't connect)." >&2
        echo "[aw5d-lcd]        run from a desktop login, or set XDG_RUNTIME_DIR first:" >&2
        echo "[aw5d-lcd]          export XDG_RUNTIME_DIR=/run/user/\$(id -u)" >&2
        exit 1
    fi

    log "installing driver -> $SHARE_DIR"
    mkdir -p "$SHARE_DIR" "$UNIT_DIR"
    install -m 0755 "$REPO_DIR/aw5d_lcd.py" "$SHARE_DIR/aw5d_lcd.py"

    # A convenient `aw5d-lcd` command on PATH. ~/.local/bin (the default) needs no sudo; a
    # system dir via AW5D_BIN_DIR (e.g. /usr/local/bin) does — write with sudo if not writable.
    launcher_body="#!/usr/bin/env bash
# aw5d-lcd launcher (generated by install.sh) — runs the driver with the detected Python.
exec \"$PYTHON\" \"$SHARE_DIR/aw5d_lcd.py\" \"\$@\""
    mkdir -p "$BIN_DIR" 2>/dev/null || sudo mkdir -p "$BIN_DIR"
    if [[ -w "$BIN_DIR" ]]; then
        printf '%s\n' "$launcher_body" > "$LAUNCHER"; chmod 0755 "$LAUNCHER"
    else
        log "launcher dir $BIN_DIR needs sudo"
        printf '%s\n' "$launcher_body" | sudo tee "$LAUNCHER" >/dev/null; sudo chmod 0755 "$LAUNCHER"
    fi
    log "installing launcher -> $LAUNCHER"
    case ":$PATH:" in
        *":$BIN_DIR:"*) : ;;
        *) log "note: $BIN_DIR isn't on your PATH — add:  export PATH=\"\$HOME/.local/bin:\$PATH\"" ;;
    esac

    # Default config (update interval etc.) — never clobber an existing one.
    mkdir -p "$HOME/.config"
    if [[ ! -f "$HOME/.config/aw5d-lcd.env" ]]; then
        install -m 0644 "$REPO_DIR/aw5d-lcd.env.example" "$HOME/.config/aw5d-lcd.env"
        log "wrote default config -> ~/.config/aw5d-lcd.env (set AW5D_INTERVAL to change update rate)"
    fi

    log "installing udev rule -> $UDEV_RULE (sudo)"
    sudo install -m 0644 "$REPO_DIR/udev/99-aw5d-lcd.rules" "$UDEV_RULE"
    sudo udevadm control --reload-rules
    sudo udevadm trigger --subsystem-match=hidraw 2>/dev/null || true

    log "installing systemd user unit -> $UNIT_DIR/$SERVICE"
    # Render the unit with the detected interpreter (robust to non-standard python paths).
    # Escape sed-special chars (& \ |) in the path so an unusual prefix can't corrupt the unit.
    py_esc=$(printf '%s' "$PYTHON" | sed -e 's/[\\&|]/\\&/g')
    sed "s|/usr/bin/python3|$py_esc|" "$REPO_DIR/systemd/$SERVICE" > "$UNIT_DIR/$SERVICE"
    chmod 0644 "$UNIT_DIR/$SERVICE"
    systemctl --user daemon-reload
    systemctl --user enable --now "$SERVICE"

    log "enabling linger (service runs without an active login)"
    loginctl enable-linger "$USER" || log "could not enable linger (non-fatal)"

    sleep 1
    if systemctl --user is-active --quiet "$SERVICE"; then
        log "running. the cooler LCD should now show live CPU stats."
        log "commands:  aw5d-lcd doctor  |  aw5d-lcd list  |  aw5d-lcd --help"
        log "no auto-update: re-run the installer (or 'just update') whenever you want the latest."
    else
        log "service is not active — check: journalctl --user -u $SERVICE -n 30"
        exit 1
    fi
}

case "${1:-}" in
    --uninstall|-u) uninstall ;;
    "" ) do_install ;;
    * ) echo "usage: $0 [--uninstall]" >&2; exit 2 ;;
esac
